### ISSUE TITLE
So... what happens when

### ISSUE THREAD

**Issue by xonecas** [tabatkins/life#4]
Someone forks your life? :)

**Comment by tabatkins** [comment]
It means we're IN THE FUTURE.

WORKSFORME

On Tue, Mar 22, 2011 at 12:06 AM, xonecas
reply@reply.github.com
wrote:

**Comment by mathiasbynens** [comment]
As long as no one [forks Tab’s DNA](https://github.com/msporny/dna/pull/1), I think we’ll be okay.
