### ISSUE TITLE
Add a CSS3 spec you’re writing to GitHub (Flexbox etc)

### ISSUE THREAD

**Issue by oli** [tabatkins/life#8]
What about upping something you’re editing here, and seeing what happens?
Hellz, you might even get some good feedback out of it!

ref: http://twitter.com/boblet/status/60634546600816641

**Comment by tabatkins** [comment]
This is a good idea.  When I start developing Positioned Layout I'll do this.

**Comment by oli** [comment]
naisu! will endeavour to send a pull req for at least one typo :)
